#!/bin/bash

set -e

# should execute from packaging/blockstack-toolbox-windows
cp ../browser-core-docker/launcher ./windows/

# check if we got an arg to set the release tag
# TAG="latest"

push=false

. versions

if [ -f secrets ]; then
    echo "Secrets file found, attempting to push to Azure blob storage"
    if [ "$BUILD_TAG" ]; then
        TAG="$BUILD_TAG"
    else
        TAG=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)
    fi
    sed -i -e "s/TAG=latest/TAG=${TAG}/" ./windows/launcher
    . secrets
    push=true
fi

docker build \
	-t windows-installer \
	-f Dockerfile.windows \
	--build-arg DOCKER_RELEASE_STAGE="${DOCKER_RELEASE_STAGE}" \
	--build-arg INSTALLER_VERSION="${INSTALLER_VERSION}" \
	--build-arg DOCKER_VERSION="${DOCKER_VERSION}" \
	--build-arg DOCKER_COMPOSE_VERSION="${DOCKER_COMPOSE_VERSION}" \
	--build-arg DOCKER_MACHINE_VERSION="${DOCKER_MACHINE_VERSION}" \
	--build-arg KITEMATIC_VERSION="${KITEMATIC_VERSION}" \
	--build-arg VBOX_VERSION="${VBOX_VERSION}" \
	--build-arg VBOX_REV="${VBOX_REV}" \
	--build-arg MIXPANEL_TOKEN="${MIXPANEL_TOKEN}" \
	.

CONTAINER="$(docker run -d windows-installer)"
mkdir -p dist
docker cp "${CONTAINER}":/installer/Output/BlockstackToolbox.exe dist/
docker rm "${CONTAINER}" 2>/dev/null || true

if [ "$push" == "true" ]; then
  echo "Pushing to azure.."
  OUTNAME=windows-installer-$TAG.exe
  az storage blob upload --file ./dist/BlockstackToolbox.exe -c packaging --name $OUTNAME --connection-string $azureConnectionString
  az storage blob url -c packaging -n $OUTNAME --connection-string $azureConnectionString
fi
